version: '3.5'
services:
  redis:
    image: redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASS}
    restart: unless-stopped
    volumes:
      - ./dispdata:/data
    ports:
      - "6379:6379"